import { Field, Int, ObjectType } from "type-graphql";
import {BaseEntity, Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn} from "typeorm";

@Entity()
@ObjectType()
export class Task extends BaseEntity{
    @PrimaryGeneratedColumn()//generated by typeorm auto
    @Field(() => Int)//specifying graphql type
    id: number;//typescript type

    @CreateDateColumn()
    @Field(() => String)
    created: Date;

    @UpdateDateColumn()
    @Field(() => String)
    updated: Date;

    @Column()
    @Field(() => String)
    title: string;

    @Column()
    @Field(() => Boolean)
    isComplete: boolean;
}